apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-mlflow
  template:
    metadata:
      labels:
        app: postgresql-mlflow
    spec:
      containers:
      - image: postgres:14.0
        name: postgres
        env:
        - name: POSTGRES_USER
          value: mlflow
        - name: POSTGRES_PASSWORD
          value: mlflow
        - name: POSTGRES_DB
          value: mlflow
        ports:
        - containerPort: 5432
          name: postgre
        volumeMounts:
        - name: postgresql-volume
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql-mlflow-pvc
